config/routes.rb
Mondiale::Application.routes.draw do

	resources :posts, except: [:show, :index]
  resources :trip_plans do
    resources :plan_items
    member do
      get :add_item
      get :choose_trip_plan
    end
  end

  resources :trips do
    member do
      get   :new_cover
      post  :create_cover
      get  :convert_trip
    end
    collection {
      post  :sort_chapter_items
    }
  	resources :chapters do
      resources :posts, except: [:index, :show] do
      end
    end
  end

  # get 'set_trip_cover/:id'  =>  'trips#set_photo',        as: :set_trip_cover
  # post 'set_trip_cover/:id' =>  'trips#set_photo_save',   as: :set_trip_cover_save

  post 'delete_picture' =>      'post_attachments#destroy', as: :delete_picture
  get 'signup'          =>      'users#new',                as: :signup
  resources :users do
    member { get 'my_trips' }
    member { get 'inspiration_list'}
    member { get 'my_trip_plans' }
  end

  get 'signin'          =>      'sessions#new',             as: :signin
  get 'signout'         =>      'sessions#destroy',         as: :signout
  resources :sessions, only: [:create]
  resources :inspirations, only: [:create, :destroy]


  root 'welcome#index'
end

app/models/trip_plan.rb
class TripPlan < ActiveRecord::Base

	has_many :plan_items
	belongs_to :user

	geocoded_by :location

	validates :title,  presence: true,
										 uniqueness: true
	validates :description, presence: true

	def add_item(type,item)
		if type == "trip"
			add_trip_inspiration(item)
		end
	end


	def add_trip_inspiration(trip)
		posts = trip.posts
		posts.each do |post|
			plan_item = self.plan_items.new(title: post.title, location: post.location)
			plan_item.save
		end
	end

end

app/controllers/trip_plans_controller.rb
class TripPlansController < ApplicationController

	before_action :set_trip_plan, only: [:show, :destroy, :edit, :update]

	def new
		@trip_plan = current_user.trip_plans.new
		respond_to do |format|
			format.html
			format.js
		end
	end

	def create
		@trip_plan = current_user.trip_plans.new(trip_plan_params)
		respond_to do |format|
			if @trip_plan.save
				format.html do
				flash[:success] = "Your trip plan has been created successfully"
	      redirect_to @trip_plan
	    	end
	    	format.js { trip_plan_path(@trip_plan) }
	    else
	    	format.html { render :new }
	      format.js {}
	    end
		end
	end

	def show
		@trip_plan = TripPlan.find(params[:id])
		@plan_items = @trip_plan.plan_items.trip_order
	end

	def destroy
		@trip_plan.destroy
		flash[:success] = "Your trip plan has been removed successfully"
		redirect_to my_trip_plans_user_path(current_user)
	end

	def edit
	end

	def update
		respond_to do |format|
			if @trip_plan.update(trip_plan_params)
				format.html {
					flash[:success] = "Your trip plan has been updated successfully"
					redirect_to @trip_plan
				}
				format.js
			else
				format.html { render :edit }
				format.js
			end
		end
	end

	def choose_trip_plan
		@trip_plans = current_user.trip_plans
		respond_to do |format|
			format.html
			format.js
		end
	end

	def add_item
		@trip_plan = TripPlan.find(params[:trip_plan_id])
		@trip_plan.add_item()
	end


private

	def set_trip_plan
		@trip_plan = TripPlan.find(params[:id])
	end

	def trip_plan_params
    params.require(:trip_plan).permit(:title, :description)
  end

end

app/views/trip_plans/_choose_trip_plan.html.erb
<div id="trip" class="form-float">
	<% @trip_plans.each do |trip_plan| %>
	<div class="form-section">
		<h1 class="form-title">Select a Trip Plan</h1>
			<div class="form-field">
			<ul>
        <li class="radio-button">
        <%= radio_button_tag :trip_plan_id, trip_plan.id %>
        <%= label_tag :trip_plan_id, trip_plan.title %>
        </li>
        <% end %>
      </ul>

      <div class="form-field">
        <%= link_to "Add to this Trip Plan", add_item_trip_plan_path(type: params[:type], item: params[:item], trip_plan_id: :trip_plan_id), class: "form-btn close" %>
        <%= link_to "Close", '#', class: "form-btn close" %>
      </div>

      </div>
	</div>
</div>

app/views/trip_plans/_form.html.erb
<div id="trip" class="form-float">
<%= form_for @trip_plan, html: { class: "form-container" } do |f| %>
  <legend class="form-title"><%= title %></legend>
  <%= render 'alerts/error_message', object: @trip_plan %>

  <div class="form-section">
    <div class="form-field">
      <%= f.text_field :title, class: "form-input", placeholder: "Trip name" %>
      <%= f.text_area :description, class: "form-input",
            placeholder: "Trip summary" %>
    </div>
    <div class="form-field">
      <%= f.submit submit, class: "form-btn" %>
      <%= link_to "Close", '#', class: "form-btn close" %>
    </div>
  </div>

<% end %>


</div>

app/views/trip_plans/_trip_plan.html.erb
<div class="large-6 columns">
	<h1 class="title"><%= link_to trip_plan.title, trip_plan, class: "link" %></h1>

	<% if trip_plan.plan_items.any? %>

			<div class="trip-plan-partial-map">
        <div class="googleMap cover-map" data-objects="<%= plan_items_in_json(trip_plan.plan_items) %>"></div>
      </div>

  <% end %>
</div>

app/views/trip_plans/choose_trip_plan.html.erb
<div id="trip" class="form-float">
	<% @trip_plans.each do |trip_plan| %>
	<div class="form-field">
		<h1 class="form-title">Select a Trip Plan</h1>
			<div class="form-section">
			<ul>
        <li class="radio-button">
        <%= radio_button_tag :trip_plan_id, trip_plan.id %>
        <%= label_tag :trip_plan_id, trip_plan.title %>
        </li>
        <% end %>
      </ul>
      </div>
	</div>
</div>

app/views/trip_plans/choose_trip_plan.js.erb
var form = $('#trip_plan.form-float');
var blurBackground = addBlur('body');
form = $('<%= j render "trip_plans/choose_trip_plan" %>');
slideDownShow(form);
clickToClose(blurBackground.add('.close'), form);

app/views/trip_plans/create.js.erb
<% if @trip.errors.any? %>
  post_fail($('<%= j render "alerts/error_message", object: @trip_plan %>'))
<% else %>
  window.location = "<%= trip_plan_path(@trip_plan) %>"
<% end %>

app/views/trip_plans/edit.html.erb
<% provide :page_title, "Edit Trip Plan" %>

<%= render 'form', title: yield(:page_title), submit: "Update Trip Plan" %>

app/views/trip_plans/edit.js.erb
var form = $('#trip.form-float');
var blurBackground = addBlur('body');
form = $('<%= j render "trip_plans/form", title: "Update Trip Plan", submit: "Update" %>');
slideDownShow(form);
clickToClose(blurBackground.add('.close'), form);

app/views/trip_plans/new.html.erb
<% provide :page_title, "New Trip Plan" %>

<%= render 'form', title: yield(:page_title), submit: "Create Trip Plan" %>

app/views/trip_plans/new.js.erb
var form = $('#trip_plan.form-float');
var blurBackground = addBlur('body');
form = $('<%= j render "trip_plans/form", title: "New Trip Plan", submit: "Create" %>');
slideDownShow(form);
clickToClose(blurBackground.add('.close'), form);

app/views/trip_plans/show.html.erb
<% if @trip_plan.user == current_user %>

<div class="plan-title">
	<h1> <%= @trip_plan.title %></h1>
	<%= link_to "", edit_trip_plan_path, class: "fa fa-edit", remote: true %>
	<%= link_to "", @trip_plan, confirm: "Are you sure you want to delete this trip plan?", method: :delete, class: "fa fa-times" %>
</div>

<div class="map-container">
		<div class="googleMap cover-map" data-objects="<%= plan_items_in_json(@plan_items) %>"></div>
</div>


<div class="description large-7 large-offset-1 columns">
		<%= @trip_plan.description %>
</div>

<div class="itinerary large-2 columns">
			<h1>Your Itinerary</h1>
				<%= link_to ' Add a new item to your itinerary', new_trip_plan_plan_item_path(@trip_plan), class: "fa fa-plus-square", remote: true %>
			<div class="plan-items">
				<%= render @plan_items %>
			</div>

</div>

<% end %>

app/views/trip_plans/show.js.erb
<% if params[:tab] == "Description" %>
		$(".plan-itinerary").addClass('hidden-tab')
		$(".plan-add-new").addClass('hidden-tab')
		$(".plan-description").removeClass('hidden-tab')
<% elsif params[:tab] == "Itinerary" %>
		$(".plan-description").addClass('hidden-tab')
		$(".plan-add-new").addClass('hidden-tab')
		$(".plan-itinerary").removeClass('hidden-tab')
<% elsif params[:tab] == "Add" %>
		$(".plan-description").addClass('hidden-tab')
		$(".plan-itinerary").addClass('hidden-tab')
		$(".plan-add-new").removeClass('hidden-tab')
<% end %>