config/routes.rb
Mondiale::Application.routes.draw do

	resources :posts, except: [:show, :index]
  resources :trip_plans do
    resources :plan_items
    member do
      get :add_item
      get :choose_trip_plan
    end
  end

  resources :trips do
    member do
      get   :new_cover
      post  :create_cover
      get  :convert_trip
    end
    collection {
      post  :sort_chapter_items
    }
  	resources :chapters do
      resources :posts, except: [:index, :show] do
      end
    end
  end

  # get 'set_trip_cover/:id'  =>  'trips#set_photo',        as: :set_trip_cover
  # post 'set_trip_cover/:id' =>  'trips#set_photo_save',   as: :set_trip_cover_save

  post 'delete_picture' =>      'post_attachments#destroy', as: :delete_picture
  get 'signup'          =>      'users#new',                as: :signup
  resources :users do
    member { get 'my_trips' }
    member { get 'inspiration_list'}
    member { get 'my_trip_plans' }
  end

  get 'signin'          =>      'sessions#new',             as: :signin
  get 'signout'         =>      'sessions#destroy',         as: :signout
  resources :sessions, only: [:create]
  resources :inspirations, only: [:create, :destroy]


  root 'welcome#index'
end

app/views/sidebar/_guest.html.erb
<ul class="menu">
  <li><%= link_to 'Featured Trips', trips_path, class: 'btn' %></li>
  <li><%= link_to 'Sign In', :signin, class: "btn", remote: true %></li>
  <li><%= link_to 'Sign Up', :signup, class: "btn" %></li>
</ul>

app/views/sidebar/_index.html.erb
<%= link_to site_name, root_path, class: 'site-logo' %>

<% if logged_in? %>
  <%= render 'sidebar/user' %>
<% else %>
  <%= render 'sidebar/guest' %>
<% end %>

app/views/sidebar/_user.html.erb
<div class="sidebar-profile">
  <%= link_to current_user.name, user_path(current_user), class: 'profile-link' %>
</div>
<ul class="menu">
  <li>
    <%= link_to new_trip_path, class: 'btn', remote: true do %>
      <span class="fa fa-plus-square"></span> Create a trip story
    <% end %>

    <%= link_to new_trip_plan_path, class: 'btn', remote: true do %>
      <span class="fa fa-plus-square"></span> Plan a trip
      <% end %>

    <%= link_to my_trips_user_path(current_user), class: 'btn' do %>
      <span class="fa fa-plane"></span> My trip stories
    <% end %>

    <%= link_to my_trip_plans_user_path(current_user), class: 'btn' do %>
      <span class="fa fa-plane"></span> My trip plans
    <% end %>

    <%= link_to inspiration_list_user_path(current_user), class: "btn" do %>
    <span class="fa fa-heart"></span> Inspiration list
    <% end %>

  </li>

  <li>
    <%= link_to trips_path, class: 'btn' do %>
      <span class="fa fa-rocket"></span> Popular trips
    <% end %>
  </li>

  <li>
    <%= link_to edit_user_path(current_user), class: 'btn' do %>
      <span class="fa fa-edit"></span> Edit account
    <% end %>
  </li>

  <li>
    <%= link_to :signout, class: "btn" do %>
    <span class="fa fa-sign-out"></span> Sign out
    <% end %>
  </li>
</ul>