config/routes.rb
Mondiale::Application.routes.draw do

	resources :posts, except: [:show, :index]
  resources :trip_plans do
    resources :plan_items
    member do
      get :add_item
      get :choose_trip_plan
    end
  end

  resources :trips do
    member do
      get   :new_cover
      post  :create_cover
      get  :convert_trip
    end
    collection {
      post  :sort_chapter_items
    }
  	resources :chapters do
      resources :posts, except: [:index, :show] do
      end
    end
  end

  # get 'set_trip_cover/:id'  =>  'trips#set_photo',        as: :set_trip_cover
  # post 'set_trip_cover/:id' =>  'trips#set_photo_save',   as: :set_trip_cover_save

  post 'delete_picture' =>      'post_attachments#destroy', as: :delete_picture
  get 'signup'          =>      'users#new',                as: :signup
  resources :users do
    member { get 'my_trips' }
    member { get 'inspiration_list'}
    member { get 'my_trip_plans' }
  end

  get 'signin'          =>      'sessions#new',             as: :signin
  get 'signout'         =>      'sessions#destroy',         as: :signout
  resources :sessions, only: [:create]
  resources :inspirations, only: [:create, :destroy]


  root 'welcome#index'
end

app/models/plan_item.rb
class PlanItem < ActiveRecord::Base

	belongs_to :trip_plan

	geocoded_by :location
	after_validation :geocode, if: :location_changed?

	scope :trip_order, -> {order(date: :asc)}

end

app/controllers/plan_items_controller.rb
class PlanItemsController < ApplicationController

	def new
		@trip_plan = TripPlan.find(params[:trip_plan_id])
		@plan_item = PlanItem.new(trip_plan_id: @trip_plan)
	end

	def create
		@trip_plan = TripPlan.find(params[:trip_plan_id])
		@plan_item = @trip_plan.plan_items.new(plan_items_params)
			respond_to do |format|
				if @trip_plan.save
					format.html do
						flash[:success] = "Your post has been created successfully"
						redirect_to @trip_plan
					end
					format.js
				else
					format.html {render :new}
					format.js
				end
			end
	end

	def edit
		@trip_plan = TripPlan.find(params[:trip_plan_id])
		@plan_item = PlanItem.find(params[:id])
	end

	def update
		@trip_plan = TripPlan.find(params[:trip_plan_id])
		@plan_items = @trip_plan.plan_items
		@plan_item = PlanItem.find(params[:id])

		respond_to do |format|
			if @plan_item.update(plan_items_params)
				format.html do
					flash[:success] = "Your Itinerary Item has been updated successfully"
					redirect_to @trip_plan
				end
				format.js
			else
				format.html {render :edit}
				format.js
			end
		end
	end

	def destroy
		@trip_plan = TripPlan.find(params[:trip_plan_id])
		@plan_item = PlanItem.find(params[:id])
		@plan_items = @trip_plan.plan_items
		respond_to do |format|
			if @plan_item.destroy
				format.html do
					flash[:success] = "This itinerary item has been deleted successfully"
					redirect_to @trip_plan
				end
				format.js
			else
				format.html
				format.js
			end
		end
	end

private

	def plan_items_params
		params.require(:plan_item).permit(:title, :date, :location)
	end

end

app/views/plan_items/_form.html.erb
<div id="post" class="form-float">
<%= form_for [@trip_plan, @plan_item], html: { class: "form-container" }  do |f| %>
  <legend class="form-title"><%= title %></legend>

	<div class="form-section">

    <div class="form-field">
      <%= f.text_field :title, class: "form-input", placeholder: "Plan item title" %>
    </div>

    <div class="form-field">
      <%= f.text_field :location, class: "form-input", placeholder: "Location" %>
      <%= f.date_select :date, class: 'form-label' %>
    </div>

    <div class="form-field">
      <%= f.submit submit, class: "form-btn" %>
      <%= link_to "Close", '#', class: "form-btn close" %>
    </div>

 </div>

<% end %>
</div>

app/views/plan_items/_plan_item.html.erb
<div id="plan-item-<%= plan_item.id %>">

	<div class="plan-item-title">
		<%= plan_item.title %>
	</div>

	<div class="plan-item-location">
		<%= plan_item.location %>
	</div>

	<div class="plan-item-date">
		<% if plan_item.date %>
			<%= plan_item.date.strftime("%Y-%m-%d") %>
		<% end %>
	</div>


	<%= link_to "", trip_plan_plan_item_path(plan_item.trip_plan, plan_item), method: :delete, confirm: "Are you sure you want to delete this item", class: "fa fa-times", title: "Delete plan item", remote: true %>
	<%= link_to "", edit_trip_plan_plan_item_path(plan_item.trip_plan, plan_item), class: "fa fa-edit", remote: true %>

</div>

app/views/plan_items/destroy.js.erb
$('.plan-items').html('<%= j render @plan_items %>')
loadMap()

app/views/plan_items/edit.html.erb
<% provide :page_title, "Edit Post" %>

<%= render 'form', title: yield(:page_title), submit: "Update" %>

app/views/plan_items/edit.js.erb
var form = $('#plan_item.form-float');
var blurBackground = addBlur('body');
form = $('<%= j render "plan_items/form", title: "Update Itinerary Item", submit: "Update" %>');
slideDownShow(form);
clickToClose(blurBackground.add('.close'), form);

app/views/plan_items/new.html.erb
<% provide :page_title, "New Plan Item" %>

<%= render 'form', title: yield(:page_title), submit: "New Plan Item" %>

app/views/plan_items/new.js.erb
var form = $('#plan_item.form-float');
var blurBackground = addBlur('body');
form = $('<%= j render "plan_items/form", title: "New Plan Item", submit: "Create" %>');
slideDownShow(form);
clickToClose(blurBackground.add('.close'), form);