config/routes.rb
Mondiale::Application.routes.draw do

	resources :posts, except: [:show, :index]
  resources :trip_plans do
    resources :plan_items
    member do
      get :add_item
      get :choose_trip_plan
    end
  end

  resources :trips do
    member do
      get   :new_cover
      post  :create_cover
      get  :convert_trip
    end
    collection {
      post  :sort_chapter_items
    }
  	resources :chapters do
      resources :posts, except: [:index, :show] do
      end
    end
  end

  # get 'set_trip_cover/:id'  =>  'trips#set_photo',        as: :set_trip_cover
  # post 'set_trip_cover/:id' =>  'trips#set_photo_save',   as: :set_trip_cover_save

  post 'delete_picture' =>      'post_attachments#destroy', as: :delete_picture
  get 'signup'          =>      'users#new',                as: :signup
  resources :users do
    member { get 'my_trips' }
    member { get 'inspiration_list'}
    member { get 'my_trip_plans' }
  end

  get 'signin'          =>      'sessions#new',             as: :signin
  get 'signout'         =>      'sessions#destroy',         as: :signout
  resources :sessions, only: [:create]
  resources :inspirations, only: [:create, :destroy]


  root 'welcome#index'
end

app/models/post.rb
class Post < ActiveRecord::Base

  mount_uploader :postimage, PostImageUploader

	belongs_to :chapter
  has_one :user, through: :chapter

	has_many :post_attachments, dependent: :delete_all
  has_many :inspirations, as: :inspirable
 	accepts_nested_attributes_for :post_attachments

  has_one :trip, through: :chapter

	validates :title,     presence: true
  validates :content,   presence: true
  validates :date,      presence: true

  geocoded_by :location
  after_validation :geocode, if: :location_changed?

  def trip_id
    trip.id
  end

  def inspiration
    if inspiration_id != nil
    ActiveModel.const_get(inspiration_type).find(inspiration_id)
    end
  end

  def already_inspired(user_id)
    inspirations.find_by(user_id: user_id)
  end

  def already_inspired?(user_id)
    already_inspired(user_id).is_a?(Inspiration)
  end

  def cover_photo
    if post_attachments.any?
      post_attachments[rand(post_attachments.size)].postimage_url
    else
      'bridge.jpg'
    end
  end

  def find_inspiration_by(obj)
    type_id = (obj.class.to_s.downcase << "_id").to_sym
    inspirations.find_by(type_id => obj.id)
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:edit, :update, :destroy, :vote]

	def new
		@chapter = Chapter.find(params[:chapter_id])
		@post = Post.new( chapter_id: @chapter.id )
   	@post_attachment = @post.post_attachments.build

   	respond_to do |format|
      format.html
      format.js
    end
	end

	def create
		@chapter = Chapter.find(params[:chapter_id])
		@post = @chapter.posts.new(post_params)
			respond_to do |format|
		if @post.save
			save_images
			format.html do
			flash[:success] = "Your post has been created successfully"
			redirect_to trip_chapter_path(@post.trip, @post.chapter)
			end
			format.js
		else
			format.html {render :new}
			format.js
		end
	 end
	end

	def edit
		@chapter = Chapter.find(params[:chapter_id])
    @post = Post.find(params[:id])
    @post_attachment = @post.post_attachments.build
	end

	def update
	@chapter = Chapter.find(params[:chapter_id])
	@posts = @chapter.posts

	respond_to do |format|
		if @post.update(post_params)
			save_images
			format.html do
				flash[:success] = "Your post has been updated successfully"
				redirect_to trip_chapter_path(@post.trip, @post.chapter)
			end
			format.js
		else
			format.html {render :edit}
			format.js
		end
	end
	end

	def destroy
		@chapter = Chapter.find(params[:chapter_id])
		respond_to do |format|
		if @post.destroy
			@posts = @chapter.posts
			format.html do
				flash[:success] = "Your post has been deleted successfully"
				redirect_to trip_chapter_path(@post.trip, @post.chapter)
			end
			format.js {flash.now[:success] = "gone"}
		else
			format.html {render :show}
			format.js
		end
		end
	end


private

	def save_images
		if params[:post_attachments]
			params[:post_attachments]['postimage'].each do |a|
	   	  @post_attachment = @post.post_attachments.create!(:postimage => a, :post_id => @post.id)
    	end
  	end
	end

	def set_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :content, :date, :location, :post_attachments, :inspiration_id, :inspiration_type)
	end

end

app/views/posts/_form.html.erb
<div id="post" class="form-float">
<%= form_for [@post.trip, @post.chapter, @post], remote: true, html: { multipart: true, class: "form-container" }  do |f| %>
  <legend class="form-title"><%= title %></legend>

  <div class="form-section">
    <div class="form-field">
      <%= f.text_field :title, class: "form-input", placeholder: "Post title" %>
      <%= f.text_area :content, class: "form-input",
            placeholder: "Post content (Markdown)" %>
    </div>

    <div class="form-field">
      <%= f.text_field :location, class: "form-input", placeholder: "Location" %>
      <%= f.date_select :date, class: 'form-label' %>
    </div>

    <div class="form-field">
      <% @post.post_attachments.each do |pic| %>
        <% if pic.id %>
          <div id="pic<%= pic.id %>" class="post-image">
            <%= image_tag pic.postimage_url(:thumb), class: "image" %>
            <%= link_to 'Click to remove', delete_picture_path(id: pic.id), method: :post, class: "del-pic", remote: true %>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="form-field">
      <%= f.fields_for :post_attachments do |p| %>
      <% if p.object.id.nil? %>
        <%= p.file_field :postimage, multiple: true, name: "post_attachments[postimage][]" %>
        <% end %>
      <% end %>
   </div>

    <div class="form-field">
      <%= f.submit submit, class: "form-btn" %>
      <%= link_to "Close", '#', class: "form-btn close" %>
    </div>
 </div>

  <div class="inspirations">
    <h3>Inspirations</h3>
    <ul>
      <% current_user.inspirations.where(inspirable_type: "Post").each do |inspiration| %>
        <li class="radio-button">
        <%= f.radio_button :inspiration_id, inspiration.id %>
        <%= f.label :inspiration_id, inspiration.inspired_by.title %>
        </li>
        <% end %>
      </ul>
  </div>



<% end %>
</div>

app/views/posts/_post.html.erb
<div id="post-<%= post.id %>">
<div class="row">

	<div class = "columns large-2">

		<p class = "post-title"><%= post.title %></p>

		<!-- Inspirations -->
		<div class="post-title">
			<div class = "pi" id='post-inspiration-count-<%= post.id %>'>
				<%= render 'inspirations/inspiration_btn', object: post %>
			</div>
		</div>

		<!-- Show inspired by -->
		<% inspiration = inspiration_find(post) %>
			<% if inspiration %>
				<p>inspired by<%= link_to inspiration.title, trip_chapter_path(inspiration.trip, inspiration.chapter) %></p>
			<% end %>


		<!-- Float Control -->
		<% if post.trip.user == current_user %>
		<div class="control">
			<%= link_to "", edit_trip_chapter_post_path(post.trip, post.chapter, post), class: "fa fa-edit", remote: true %>
			<%= link_to "", trip_chapter_post_path(post.trip, post.chapter, post), method: :delete, confirm: "Are you sure you want to delete this post?", class: "fa fa-times", title: "Delete post", remote: true %>
		</div>
		<% end %>



	</div>

	<div class="columns large-9">
		<div class="post-text">
			<%= markdown(post.content) %>
		</div>
	</div>

	<div class="colums large-1">&nbsp</div>

</div>


<% if post.post_attachments.any? %>
<div class="image-row">
	<div class="post-image large-12 columns">
		<% post.post_attachments.each do |pic| %>
		<%= image_tag pic.postimage_url(:big), class: "post-image" %>
		<% end %>
	</div>
</div>
<% end %>





</div>

app/views/posts/create.js.erb
<% if @post.errors.any? %>
  post_fail($('<%= j render "alerts/error_message", object: @post %>'))
<% else %>
  post_success($('<%= j render @post %>'),'post', '.posts')
<% end %>

app/views/posts/destroy.js.erb
$('.posts').html('<%= j render @posts %>')

app/views/posts/edit.js.erb
var form = $('#post.form-float');
var blurBackground = addBlur('body');
form = $('<%= j render "posts/form", title: "Update Post", submit: "Update" %>');
slideDownShow(form);
clickToClose(blurBackground.add('.close'), form);

app/views/posts/new.html.erb
<% provide :page_title, "New post" %>

<%= render 'form', title: yield(:page_title), submit: "Post" %>

app/views/posts/new.js.erb
var form = $('#post.form-float');
var blurBackground = addBlur('body');
form = $('<%= j render "posts/form", title: "New Post", submit: "Create" %>');
slideDownShow(form);
clickToClose(blurBackground.add('.close'), form);

app/views/posts/update.js.erb
<% if @post.errors.any? %>
  post_fail($('<%= j render "alerts/error_message", object: @post %>'))
<% else %>
  var form = $('#post.form-float');
  slideUpRemove(form);
  removeBlur();

  $('#post-' + <%= @post.id %>).replaceWith('<%= j render @post %>');

<% end %>